// import type { StrapiApp } from "@strapi/strapi/admin";

export default {
  config: {
    locales: [
      // 'ar',
      // 'fr',
      // 'cs',
      // 'de',
      // 'dk',
      // 'es',
      // 'he',
      // 'id',
      // 'it',
      // 'ja',
      // 'ko',
      // 'ms',
      'nl',
      // 'no',
      // 'pl',
      // 'pt-BR',
      // 'pt',
      // 'ru',
      // 'sk',
      // 'sv',
      // 'th',
      // 'tr',
      // 'uk',
      // 'vi',
      // 'zh-Hans',
      // 'zh',
    ],
    translations: {
      nl: {
        shared: 'Sections',
        introduction: 'Inleiding',
        application: 'Aanvraag',
        proof: 'Bewijs',
        conditions: 'Voorwaarden',
        objection: 'Bezwaar',
        costs: 'Kosten',
        term: 'Termijn',
        'what to do if no respons': 'Wat te doen bij geen reactie',
        details: 'Bijzonderheden',
        contact: 'Contact',
      },
    },
  },
  bootstrap(/*app: StrapiApp*/) {},
};
